public enum EstadoPaciente {
    INDO_TOTEM,
    INDO_CADEIRA_TRIAGEM,
    AGUARDANDO_TRIAGEM,
    INDO_TRIAGEM,
    EM_TRIAGEM,
    INDO_CADEIRA_CONSULTA,
    AGUARDANDO_CONSULTA,
    INDO_CONSULTA,
    EM_CONSULTA,
    INDO_SAIDA
}